version: 2.1

commands:
  run-fail-fast:
    description: "Execute command and fail on any warning in output"
    parameters:
      command:
        type: string
    steps:
      - run: << parameters.command >> 2>&1 | tee output.log
      - run: |
          if grep -q "warning:" output.log; then
            echo "Warnings found in test output. Failing the job."
            exit 1
          fi
jobs:
  build:
    parameters:
      docker-image:
        type: string
      gemfile:
        type: string
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - run: ruby --version
      - when:
          condition:
            equal: ["jruby:latest", << parameters.docker-image >>]
          steps:
            - run: apt-get update
            - run: apt-get install -y git
      - run: gem --version
      - run: bundle --version
      - run: bundle install --gemfile=<< parameters.gemfile >>
      - run: |
          if [ "<< parameters.docker-image >>" > "ruby:2.2" ]; then
            export RUBYOPT="--enable-frozen-string-literal"
          fi
      - when:
          condition:
            equal: ["Gemfile", << parameters.gemfile >>]
          steps:
            - run-fail-fast:
                command: bundle exec rake test
      - when:
          condition:
            matches:
              pattern: ".*minitest.*"
              value: << parameters.gemfile >>
          steps:
            - run-fail-fast:
                command: MOCHA_RUN_INTEGRATION_TESTS=minitest bundle exec --gemfile=<< parameters.gemfile >> rake test
      - when:
          condition:
            matches:
              pattern: ".*test-unit.*"
              value: << parameters.gemfile >>
          steps:
            - run-fail-fast:
                command: MOCHA_RUN_INTEGRATION_TESTS=test-unit bundle exec --gemfile=<< parameters.gemfile >> rake test
      - when:
          condition:
            and:
              - equal: ["ruby:latest", << parameters.docker-image >>]
              - equal: ["Gemfile", << parameters.gemfile >>]
          steps:
            - run-fail-fast:
                command: bundle exec rake test:performance
            - run: MOCHA_GENERATE_DOCS=1 bundle install --gemfile=<< parameters.gemfile >>
            - run: RUBYOPT=--disable-frozen-string-literal MOCHA_GENERATE_DOCS=1 rake docs docs:coverage
  lint:
    docker:
      - image: ruby:3.3
    steps:
      - checkout
      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: bundle install --gemfile=gemfiles/Gemfile.rubocop
      - run: bundle exec --gemfile=gemfiles/Gemfile.rubocop rake lint

workflows:
  build-all:
    jobs: &all-jobs
      - lint
      - build:
          matrix:
            parameters:
              docker-image:
                - ruby:2.2
                - ruby:2.3
                - ruby:2.4
                - ruby:2.5
                - ruby:2.6
                - ruby:2.7
                - ruby:3.0
                - ruby:3.1
                - ruby:3.2
                - ruby:3.3
                - ruby:3.4
                - ruby:latest
                - jruby:latest
              gemfile:
                - Gemfile
      - build:
          matrix:
            parameters:
              docker-image:
                - ruby:latest
              gemfile:
                - gemfiles/Gemfile.minitest.latest
                - gemfiles/Gemfile.test-unit.latest
  weekly:
    triggers:
      - schedule:
          cron: "0 3 * * 0"
          filters:
            branches:
              only:
                - main
    jobs: *all-jobs
